# Generated by Django 4.1.2 on 2023-03-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingapp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=12)),
            ],
        ),
    ]
