# Generated by Django 4.1.2 on 2023-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingapp', '0004_rename_signup_signn_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='signn',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signn',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signn',
            name='gender',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='signn',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='signn',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signn',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='signn',
            name='qualification',
            field=models.TextField(blank=True),
        ),
    ]
