# Generated by Django 4.1.7 on 2023-05-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datingapp', '0006_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='Request_users',
        ),
    ]
