# Generated by Django 4.1.7 on 2023-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datingapp', '0010_remove_signn_username_alter_block_id_alter_like_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signn',
            name='status',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
